FROM node:22.14.0-alpine

# PNPM Configuration
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json ./
RUN pnpm install

# Copy the rest of the app
COPY . .

EXPOSE 3000

CMD [ "pnpm", "start:dev", "--host", "0.0.0.0" ]
