FROM node:22.14.0-alpine

# PNPM Configuration
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy the rest of the app
COPY . .

RUN pnpx prisma generate

EXPOSE 3030

CMD ["pnpm", "start:dev"]
