FROM node:22.14-alpine

# PNPM Configuration
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json ./
RUN pnpm install

# Copy the rest of the app

COPY . .

EXPOSE 3030

CMD ["sh", "-c", "pnpm db:deploy && pnpm start:dev"]
