GET {{BASE_URL}}/training-plans?search=training&limit=10&offset=0&sortBy=name&sortOrder=asc

###

GET {{BASE_URL}}/training-plans/9747c7a4-fd9a-42ad-83c8-8dc8533c5eaf
###

POST {{BASE_URL}}/training-plans
content-type: application/json

{
  "name": "Test 2",
  "description": "",
  "weeks": 4
}

###

PUT {{BASE_URL}}/training-plans/9747c7a4-fd9a-42ad-83c8-8dc8533c5eaf
content-type: application/json

{
  "name": "Training Plan 2",
  "description": "Training Plan 2 Description Updated"
}

###

DELETE {{BASE_URL}}/training-plans/08d25b14-853f-4b6a-be99-7a1051c7061b

###
