GET {{BASE_URL}}/training-plan-weeks?trainingPlanId=9747c7a4-fd9a-42ad-83c8-8dc8533c5eaf

###

POST {{BASE_URL}}/training-plan-weeks
content-type: application/json

{
  "trainingPlanId": "9747c7a4-fd9a-42ad-83c8-8dc8533c5eaf"
}

###

DELETE {{BASE_URL}}/training-plan-weeks/f2738c91-b62e-4c2b-92ba-7577ef70d509

###
