GET {{BASE_URL}}/training-plan-weeks?trainingPlanId=9747c7a4-fd9a-42ad-83c8-8dc8533c5eaf

###

POST {{BASE_URL}}/training-plan-weeks
content-type: application/json

{
  "trainingPlanId": "9747c7a4-fd9a-42ad-83c8-8dc8533c5eaf"
}

###

DELETE {{BASE_URL}}/training-plan-weeks/29c9e01d-4e9b-408f-a1ae-4eb0f7592e6d

###
